jobs:
  emulator-test:
    env:
      api-level: 30
    name: Emulator Test
    needs: static-analysis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache Gradle
      uses: actions/cache@v4
      with:
        key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
    - continue-on-error: true
      name: Configure parallel build
      run: echo "org.gradle.parallel=true" >> local.properties
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew assemblePlayDebugAndroidTest
    - continue-on-error: true
      name: Enable KVM group perms
      run: 'echo ''KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"''
        | sudo tee /etc/udev/rules.d/99-kvm4all.rules

        sudo udevadm control --reload-rules

        sudo udevadm trigger --name-match=kvm

        '
    - continue-on-error: true
      name: Android Emulator test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ env.api-level }}
        channel: canary
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
          -no-boot-anim -camera-back none
        force-avd-creation: false
        script: bash .github/workflows/runEmulatorTests.sh
        target: aosp_atd
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: app/build/reports/androidTests/connected/flavors/PLAY/
    timeout-minutes: 45
  static-analysis:
    name: Static Code Analysis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache Gradle
      uses: actions/cache@v4
      with:
        key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
    - continue-on-error: true
      name: Configure parallel build
      run: echo "org.gradle.parallel=true" >> local.properties
    - continue-on-error: true
      name: XML code style
      run: 'curl -s -L https://github.com/ByteHamster/android-xml-formatter/releases/download/1.1.0/android-xml-formatter.jar
        > android-xml-formatter.jar

        find . -wholename "*/res/layout/*.xml" | xargs java -jar android-xml-formatter.jar

        test $(git diff | wc -l) -eq 0 || (echo -e "\n\n===== Found XML code style
        violations! See output below how to fix them. =====\n\n" && git --no-pager
        diff --color=always && false)

        '
    - continue-on-error: true
      name: Checkstyle, Lint, SpotBugs
      run: ./gradlew checkstyle :app:lintPlayDebug spotbugsPlayDebug spotbugsDebug
    - continue-on-error: true
      if: failure()
      name: Generate readable error messages for GitHub
      run: 'git diff --name-only | xargs -I ''{}'' echo "::error file={},line=1,endLine=1,title=XML
        Format::Run android-xml-formatter.jar on this file or view CI output to see
        how it should be formatted."

        python .github/workflows/errorPrinter.py

        '
    timeout-minutes: 45
  unit-test:
    name: 'Unit Test: ${{ matrix.variant }}'
    needs: static-analysis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache Gradle
      uses: actions/cache@v4
      with:
        key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
    - continue-on-error: true
      name: Configure parallel build
      run: echo "org.gradle.parallel=true" >> local.properties
    - continue-on-error: true
      name: Create temporary release keystore
      run: keytool -noprompt -genkey -v -keystore "app/keystore" -alias alias -storepass
        password -keypass password -keyalg RSA -validity 10 -dname "CN=antennapod.org,
        OU=dummy, O=dummy, L=dummy, S=dummy, C=US"
    - continue-on-error: true
      name: Build
      run: ./gradlew assemble${{ matrix.variant }}
    - continue-on-error: true
      if: matrix.execute-tests == true
      name: Test
      run: ./gradlew test${{ matrix.variant }}UnitTest test${{ matrix.base-variant
        }}UnitTest
    - continue-on-error: true
      if: matrix.upload-artifact == true
      uses: actions/upload-artifact@v4
      with:
        name: app-play-debug.apk
        path: app/build/outputs/apk/play/debug/app-play-debug.apk
    strategy:
      matrix:
        include:
        - base-variant: Debug
          execute-tests: true
          upload-artifact: true
          variant: PlayDebug
        - base-variant: Release
          execute-tests: true
          upload-artifact: false
          variant: PlayRelease
        - base-variant: Release
          execute-tests: false
          upload-artifact: false
          variant: FreeRelease
    timeout-minutes: 45
  wrapper-validation:
    name: Gradle Wrapper Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v2
    timeout-minutes: 45
name: Checks
on:
  repository_dispatch:
    types: trigger-ga___checks.yml
