jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v5
      with:
        close-issue-label: 'Close reason: No reply'
        close-issue-message: This issue was closed because we didn't get a reply for
          14 days.
        close-pr-label: 'Close reason: No reply'
        close-pr-message: This PR was closed because we didn't get a reply for 14
          days.
        days-before-close: 7
        days-before-stale: 7
        labels-to-remove-when-unstale: 'Needs: Reply'
        only-labels: 'Needs: Reply'
        stale-issue-label: 'Needs: Reply still'
        stale-issue-message: This issue will be closed when we don't get a reply within
          7 days.
        stale-pr-label: 'Needs: Reply still'
        stale-pr-message: This PR will be closed when we don't get a reply within
          7 days.
name: Close issue/PR if no reply
on:
  repository_dispatch:
    types: trigger-ga___close-if-no-reply.yml
permissions:
  issues: write
  pull-requests: write
